# Streamlit secrets configuration
# This file is optional and can be used for configuration

# Example: Enable/disable export functionality
# show_export = true

# Example: Database connection strings
# database_url = "your_database_url_here"

# Example: API keys
# api_key = "your_api_key_here"
